### ISSUE TITLE
[Dev] Implement static structure and style of the page with placeholder content

### ISSUE THREAD

**Issue by DongTianjia** [info442-su23/f-team#26]

**Comment by EloraHob** [comment]
**BLOCKER:** DUE TO API LIMITATIONS, WE ARE UNABLE TO POPULATE VARIABLE WEBPAGES WITH RESPONSE DATA. API ONLY RETURNS SHORTENED DESCRIPTION AND LINK TO THIRD PARTY WEBPAGE WITH DRUG INFO.

**SOLUTION:** INSTEAD OF USING MED CARDS TO ROUTE TO A VARIABLE WEBPAGE, WE WILL USE MED CARDS TO ROUTE DIRECTLY TO LINK PROVIDED BY API. THIS MEANS WE WILL NO LONGER HAVE CONTROL OVER PAGE STRUCTURE OR CONTENT OF INFORMATIONAL PAGES.

**Comment by EloraHob** [comment]
**BLOCKER:** DUE TO API LIMITATIONS, WE ARE UNABLE TO POPULATE VARIABLE WEBPAGES WITH RESPONSE DATA. API ONLY RETURNS SHORTENED DESCRIPTION AND LINK TO THIRD PARTY WEBPAGE WITH DRUG INFO.

**SOLUTION:** INSTEAD OF USING MED CARDS TO ROUTE TO A VARIABLE WEBPAGE, WE WILL USE MED CARDS TO ROUTE DIRECTLY TO LINK PROVIDED BY API. THIS MEANS WE WILL NO LONGER HAVE CONTROL OVER PAGE STRUCTURE OR CONTENT OF INFORMATIONAL PAGES. 

STATUS: Marking issue as NOT PLANNED due to reasons described above.

**Comment by EloraHob** [comment]
**BLOCKER:** DUE TO API LIMITATIONS, WE ARE UNABLE TO POPULATE VARIABLE WEBPAGES WITH RESPONSE DATA. API ONLY RETURNS SHORTENED DESCRIPTION AND LINK TO THIRD PARTY WEBPAGE WITH DRUG INFO.

**SOLUTION:** INSTEAD OF USING MED CARDS TO ROUTE TO A VARIABLE WEBPAGE, WE WILL USE MED CARDS TO ROUTE DIRECTLY TO LINK PROVIDED BY API. THIS MEANS WE WILL NO LONGER HAVE CONTROL OVER PAGE STRUCTURE OR CONTENT OF INFORMATIONAL PAGES. 

STATUS: Marking issue as NOT PLANNED due to reasons described above.
