### ISSUE TITLE
[Dev] Replace placeholder content with data fetched from API

### ISSUE THREAD

**Issue by DongTianjia** [info442-su23/f-team#27]
Remember to implement error code and error message feedback for rejected request

**Comment by DongTianjia** [comment]
Remember to implement error code and error message feedback for rejected request

**Comment by EloraHob** [comment]
Error code & Error message handling might be worth making a separate issue, what do you think?

**Comment by DongTianjia** [comment]
I normally think of all different cases at once (if request is successful or not) and write a complete try and catch with if and else branches (if that makes sense). We can definitely take it out as a separate issue, whichever is easier for you!

**Comment by EloraHob** [comment]
Oh, that actually makes sense. Thank you for clarifying!

**Comment by EloraHob** [comment]
**BLOCKER:** DUE TO API LIMITATIONS, WE ARE UNABLE TO POPULATE VARIABLE WEBPAGES WITH RESPONSE DATA. API ONLY RETURNS SHORTENED DESCRIPTION AND LINK TO THIRD PARTY WEBPAGE WITH DRUG INFO.

**SOLUTION:** INSTEAD OF USING MED CARDS TO ROUTE TO A VARIABLE WEBPAGE, WE WILL USE MED CARDS TO ROUTE DIRECTLY TO THE URLs PROVIDED BY API. THIS MEANS WE WILL NO LONGER HAVE CONTROL OVER PAGE STRUCTURE OR CONTENT OF INFORMATIONAL PAGES. **_AS SUCH, THERE IS NO PLACEHOLDER CONTENT TO REPLACE._** 

STATUS: Marking issue as NOT PLANNED due to reasons described above.
